// java program to perform arithmethic operation
public class OperatorExample
{  
    public static void main(String args[])
    {
    int a=10;  
    int b=5;  
    System.out.println(a+b);//15  addition
    System.out.println(a-b);//5  substruction
    System.out.println(a*b);//50 multiplication 
    System.out.println(a/b);//2 division 
    System.out.println(a%b);//0 modulus  
    }}  
